#ifndef SYSTEM_CONFIG_VALUES_H
#define SYSTEM_CONFIG_VALUES_H

#define SYSTEM_MAIN_LOOP_PERIOD_MS  (10U)     /* 10 ms = 100 Hz */
#define SYSTEM_MAIN_LOOP_PERIOD_US   (10000U)
#define SYSTEM_MAIN_LOOP_PERIOD_S    (0.01f)
#define SYSTEM_MAIN_LOOP_FREQUENCY_HZ (100U)

#endif // SYSTEM_CONFIG_VALUES_H
